### ISSUE TITLE
gnuradio 3.10 compatibility SWIG -> PyBind11

### ISSUE THREAD

**Issue by jpedrick** [sandialabs/gr-sandia_utils#11]
GNURadio 3.10 removed SWIG and replaced it with PyBind11. 

Currently, gr-sandia_utils can't be compiled with GNURadio 3.10 due to this breaking change.

**Comment by samwhiting-snl** [comment]
We now have a `maint-3.10` branch which addresses this issue. Let us know if you have any trouble with the new branch.
