### ISSUE TITLE
Build not honoring ENABLE_PYTHON=OFF

### ISSUE THREAD

**Issue by boogachamp** [sandialabs/gr-sandia_utils#2]
When disabling Python/Swig gnuradio support the build fails.

Used cmake -DENABLE_PYTHON:BOOL=OFF flag to set

Fixed locally by wrapping the addition of subdirectories:

if (ENABLE_PYTHON)
add_subdirectory(swig)
add_subdirectory(python)
endif(ENABLE_PYTHON)

**Comment by jacobgilbert-snl** [comment]
Fixed with dda4a8c3c20c28f9cd180091f7739c6b906fd491
