### ISSUE TITLE
Having placeholders _1, _2, etc. in global namespace is deprecated in boost

### ISSUE THREAD

**Issue by beroset** [sandialabs/gr-sandia_utils#8]
As of boost version 1.73, it no longer puts the placeholders _1, _2, etc. into the global namespace.  
See https://www.boost.org/doc/libs/1_73_0/boost/bind.hpp for details.  While it would be possible to add a `#define BOOST_BIND_GLOBAL_PLACEHOLDERS` to preserve the existing behavior, the better long term fix is to use the namespace instead.

**Comment by samwhiting-snl** [comment]
We've updated to GNURadio 3.10 (see the `maint-3.10` branch) which addresses this same issue by using `std::function` instead of boost in these cases.

**Comment by beroset** [comment]
Super!  This is the better way to fix it.
